### ISSUE TITLE
dull colours

### ISSUE THREAD

**Issue by jakeHooleyARU** [jakeHooleyARU/Rainbow-Poem#1]
- [x] - create a 'dull' branch for the work.
- [x] - add beige to the poem
- [x] - add ivory to the poem
- [x] - add khaki 
- [x] - take out all those nasty primary colours

**Comment by jakeHooleyARU** [comment]
something about the colour grey

**Comment by jakeHooleyARU** [comment]
i have created a dull branch[1]

**Comment by osmart** [comment]
@jakeHooleyARU your initial comment has not created a task list. 
To create a task use the 'Add to task list' button
![Screenshot 2020-02-04 at 17 02 05](https://user-images.githubusercontent.com/8986794/73768273-a2b68000-4770-11ea-8fe0-cf3e352dc3b9.png)

This will help you produce markdown like:
```
- [ ] task 1
- [ ] task 2
```
These are then rendered as checkboxes:
- [ ] task 1
- [ ] task 2

**Comment by osmart** [comment]
Great - the commit messages reference the issue and subtasks ticked off.
